version: '3.8'

services:
  myapp:
    build: .
    image: myimage
    ports:
      - "8000:8000"
    volumes:
      - /apidon:/app/data
    environment:
      - SECRETAPIKEY=8GcgX5F_vnV5NoU-9uMyGp0Ma7aVckRJCYDcGYZJAOQ

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - myapp
